### ISSUE TITLE
module six is not installed on Windows 10 by defaul

### ISSUE THREAD

**Issue by vstadnytskyi** [friedrich-schotte/EPICS_CA#4]
six is not installed on Windows 10 by default. It needs to be included as a dependency.

```
>>> CA.caput('NIH:SYRINGE.VAL',25)
WARNING:root:No module named 'six'
Traceback (most recent call last):
  File "C:\Python37-32\lib\site-packages\EPICS_CA\CA.py", line 611, in camonitor_loop
    process_replies(1.0)
  File "C:\Python37-32\lib\site-packages\EPICS_CA\CA.py", line 908, in process_replies
    process_pending_write_requests()
  File "C:\Python37-32\lib\site-packages\EPICS_CA\CA.py", line 980, in process_pending_write_requests
    data = network_data(pv.write_data, data_type)
  File "C:\Python37-32\lib\site-packages\EPICS_CA\CA.py", line 1657, in network_data
    if isarray(value):
  File "C:\Python37-32\lib\site-packages\EPICS_CA\CA.py", line 1686, in isarray
    from six import string_types
ModuleNotFoundError: No module named 'six'
```

**Comment by tacaswell** [comment]
Closed by #5
